import Navbar from "./Navbar";
import Head from "next/head";
import React from "react";

interface InputProps {
  children: React.ReactElement;
}

const Layout: React.FC<InputProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Outrigger Canoe Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <>{children}</>
    </>
  );
};

export default Layout;
